- name: Import the Elasticsearch GPG key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
    fingerprint: 4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4

- name: Add Elasticsearch repository
  copy:
    src: "templates/centosrepo.j2"  
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install Elasticsearch
  yum:
    name: elasticsearch
    enablerepo: elasticsearch
    state: present
  notify:
    - Start Elasticsearch