- name: Import the Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elasticsearch

- name: Install required packages
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
    
- name: Copy Elasticsearch configuration file
  copy: 
    src: "files/elasticsearch.yml"
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - Restart Elasticsearch

- name: Copy Elasticsearch configuration file
  copy: 
    src: "files/jvm.options"
    dest: /etc/elasticsearch/jvm.options
  notify:
    - Restart Elasticsearch

- name: Ensure Elasticsearch is started and enabled at boot time
  service:
    name: elasticsearch
    state: started
    enabled: yes