---
    - name: Insall Elasticsearch on Debian
      include: debian.yml
      when: ansible_facts['os_family'] == "Debian"
    
    
    - name: Insall Elasticsearch on  CentOS
      include: centos.yml
      when: ansible_facts['os_family'] == "RedHat"


